<?php

namespace Database\Seeders\Demo;

use App\Models\Breed;
use Illuminate\Database\Seeder;

class BreedSeeder extends Seeder
{
    public function run(): void
    {
        Breed::factory()->createMany([
            ['breed' => 'アジアン'],
            ['breed' => 'アジアンセミロングヘア'],
            ['breed' => 'アビシニアン'],
            ['breed' => 'アメリカンカール'],
            ['breed' => 'アメリカンショートヘア'],
            ['breed' => 'アメリカンボブテイル'],
            ['breed' => 'アメリカンワイヤーヘア'],
            ['breed' => 'アラビアンマウ'],
            ['breed' => 'ウクラニアン・レフコイ'],
            ['breed' => 'エーゲ・キャット'],
            ['breed' => 'エキゾチックショートヘア'],
            ['breed' => 'エジプシャンマウ'],
            ['breed' => 'オーストラリアンミスト'],
            ['breed' => 'オシキャット'],
            ['breed' => 'オホースアズーレス'],
            ['breed' => 'オリエンタル・バイカラー'],
            ['breed' => 'オリエンタルショートヘア'],
            ['breed' => 'オリエンタルロングヘア'],
            ['breed' => 'カオマニー'],
            ['breed' => 'カラーポイントショートヘアー'],
            ['breed' => 'カリフォルニア・スパングルド'],
            ['breed' => 'キムリック'],
            ['breed' => 'クリルアイランドボブテイル'],
            ['breed' => 'コーニッシュレックス'],
            ['breed' => 'コラット'],
            ['breed' => 'サイベリアン'],
            ['breed' => 'サバンナ'],
            ['breed' => 'ジャパニーズボブテイル'],
            ['breed' => 'シャム'],
            ['breed' => 'シャルトリュー'],
            ['breed' => 'シンガプーラ'],
            ['breed' => 'スコティッシュフォールド'],
            ['breed' => 'スノーシュー'],
            ['breed' => 'スフィンクス'],
            ['breed' => 'セルカークレックス'],
            ['breed' => 'セレンゲティ'],
            ['breed' => 'ソコケ'],
            ['breed' => 'ソマリ'],
            ['breed' => 'ターキッシュアンゴラ'],
            ['breed' => 'ターキッシュバン'],
            ['breed' => 'タイ'],
            ['breed' => 'チャウシー'],
            ['breed' => 'デボンレックス'],
            ['breed' => 'トイガー'],
            ['breed' => 'トンキニーズ'],
            ['breed' => 'ネベロング'],
            ['breed' => 'ノルウェージャンフォレストキャット'],
            ['breed' => 'ハイランダー'],
            ['breed' => 'バーマン'],
            ['breed' => 'バーミーズ'],
            ['breed' => 'バーミラ'],
            ['breed' => 'ハバナ'],
            ['breed' => 'バリニーズ'],
            ['breed' => 'ピクシーボブ'],
            ['breed' => 'ピーターボールド'],
            ['breed' => 'ヒマラヤン'],
            ['breed' => 'ブリティッシュショートヘア'],
            ['breed' => 'ブリティッシュロングヘア'],
            ['breed' => 'ペルシャ'],
            ['breed' => 'ベンガル'],
            ['breed' => 'ボンベイ'],
            ['breed' => 'マンクス'],
            ['breed' => 'マンチカン'],
            ['breed' => 'ミンスキン'],
            ['breed' => 'メインクーン'],
            ['breed' => 'ヨークチョコレート'],
            ['breed' => 'ヨーロピアンショートヘア'],
            ['breed' => 'ヨーロピアンバーミーズ'],
            ['breed' => 'ラガマフィン'],
            ['breed' => 'ラグドール'],
            ['breed' => 'ラパーマ'],
            ['breed' => 'ロシアンブルー'],
            ['breed' => 'ロシアンホワイト'],
            ['breed' => 'ポリダクティル・キャット'],
            ['breed' => 'バンビーノ'],
            ['breed' => 'ブラジリアン・ショートヘア'],
            ['breed' => '三毛猫'],
            ['breed' => 'en:Chantilly-Tiffany cat'],
            ['breed' => 'チートー'],
            ['breed' => 'ドメスティック・ショートヘア'],
            ['breed' => 'ドンスコイ'],
            ['breed' => 'ドラゴン・リー'],
            ['breed' => 'ドウェルフ'],
            ['breed' => 'ジャーマンレックス'],
            ['breed' => 'ジャバニーズ'],
            ['breed' => 'メコンボブテイル'],
            ['breed' => 'ナポレオン'],
            ['breed' => 'en:Oregon Rex'],
            ['breed' => 'en:Ussuri (cat)'],
            ['breed' => 'en:Ukunna'],
        ]);
    }
}
